save_dir: yolov9/gelan-c-seg
epochs: 100
batch_size: 32
weights: /kaggle/working/yolov9/gelan-c-seg.pt
single_cls: false
evolve: false
data: data.yaml
cfg: /kaggle/working/yolov9/models/segment/gelan-c-seg.yaml
resume: false
noval: false
nosave: false
workers: 8
freeze: []
mask_ratio: 0.5
no_overlap: true
close_mosaic: 10
hyp:
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 7.5
  cls: 0.5
  cls_pw: 1.0
  obj: 0.7
  obj_pw: 1.0
  dfl: 1.5
  iou_t: 0.2
  anchor_t: 5.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.9
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.15
  copy_paste: 0.3
